# Generated by Django 5.2.17 on 2026-10-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=50)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('success', models.BooleanField(default=True)),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('window', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MetricSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cpu', models.FloatField()),
                ('memory', models.FloatField()),
                ('rx_rate', models.FloatField()),
                ('tx_rate', models.FloatField()),
                ('rx_mb', models.FloatField()),
                ('tx_mb', models.FloatField()),
                ('uptime', models.FloatField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
