# Generated by Django 5.2.17 on 2026-10-10 20:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_domainexpiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainexpiry',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicesetting',
            name='domain_expiry_interval_days',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddField(
            model_name='servicesetting',
            name='domain_expiry_last_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicesetting',
            name='domain_expiry_scheduler_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicesetting',
            name='domain_expiry_send_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='servicesetting',
            name='encrypted_mattermost_webhook_url',
            field=models.TextField(blank=True),
        ),
    ]
