# Generated by Django 5.2.17 on 2026-10-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_domainexpiry_last_notified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesetting',
            name='domain_expiry_monitored_domains',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
